
const PUBLIC_WELCOME_ORDER_KEY='papaGolfGuestWelcomeOrderV1';
function menuOrder(){try{const v=JSON.parse(localStorage.getItem(PUBLIC_WELCOME_ORDER_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function applyMenuOrder(){const list=document.querySelector('[data-reorder-list="welcome"]');if(!list)return;const rows=[...list.querySelectorAll('[data-menu-key]')],byKey=new Map(rows.map(x=>[x.dataset.menuKey,x])),order=menuOrder();order.forEach(k=>{const row=byKey.get(k);if(row)list.appendChild(row)});rows.filter(x=>!order.includes(x.dataset.menuKey)).forEach(x=>list.appendChild(x));const system=list.querySelector('.system-menu-tile');if(system)list.appendChild(system)}
function saveMenuOrder(list){try{localStorage.setItem(PUBLIC_WELCOME_ORDER_KEY,JSON.stringify([...list.querySelectorAll('[data-menu-key]')].map(x=>x.dataset.menuKey)))}catch{}}
function setupMenuReorder(){
  const list=document.querySelector('[data-reorder-list="welcome"]');if(!list||list.dataset.reorderReady==='1')return;
  applyMenuOrder();list.dataset.reorderReady='1';let drag=null;
  const animateReflow=before=>{[...list.querySelectorAll('[data-menu-key]')].forEach(row=>{const prev=before.get(row);if(!prev)return;const next=row.getBoundingClientRect(),dy=prev.top-next.top;if(Math.abs(dy)<1)return;row.animate([{transform:`translateY(${dy}px)`},{transform:'translateY(0)'}],{duration:180,easing:'cubic-bezier(.2,.8,.2,1)'})})};
  const movePlaceholder=(hit,clientY)=>{if(!drag||!hit||hit===drag.active||hit.parentElement!==list||hit.classList.contains('system-menu-tile'))return;const before=new Map([...list.querySelectorAll('[data-menu-key]')].map(row=>[row,row.getBoundingClientRect()]));const r=hit.getBoundingClientRect();list.insertBefore(drag.placeholder,clientY<r.top+r.height/2?hit:hit.nextSibling);animateReflow(before)};
  const autoScroll=clientY=>{const edge=84,max=11;if(clientY<edge)window.scrollBy(0,-Math.min(max,(edge-clientY)/5));else if(clientY>innerHeight-edge)window.scrollBy(0,Math.min(max,(clientY-(innerHeight-edge))/5))};
  list.addEventListener('pointerdown',e=>{const h=e.target.closest('.menu-drag');if(!h)return;const active=h.closest('[data-menu-key]');if(!active)return;e.preventDefault();e.stopPropagation();const r=active.getBoundingClientRect();const placeholder=document.createElement('div');placeholder.className='menu-placeholder';placeholder.style.height=`${r.height}px`;active.after(placeholder);drag={active,handle:h,placeholder,pointerId:e.pointerId,grabOffset:e.clientY-r.top};active.classList.add('is-reordering');active.style.position='fixed';active.style.left=`${r.left}px`;active.style.top=`${r.top}px`;active.style.width=`${r.width}px`;active.style.height=`${r.height}px`;active.style.margin='0';document.body.classList.add('public-menu-dragging');try{h.setPointerCapture(e.pointerId)}catch{}});
  list.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();e.stopPropagation();drag.active.style.top=`${e.clientY-drag.grabOffset}px`;autoScroll(e.clientY);const hit=document.elementsFromPoint(e.clientX,e.clientY).map(el=>el.closest?.('[data-menu-key]')).find(row=>row&&row!==drag.active&&row.parentElement===list);movePlaceholder(hit,e.clientY)});
  const finish=e=>{if(!drag)return;e?.preventDefault();e?.stopPropagation();const {active,handle,placeholder,pointerId}=drag,target=placeholder.getBoundingClientRect();active.style.transition='top 150ms cubic-bezier(.2,.8,.2,1), left 150ms cubic-bezier(.2,.8,.2,1), transform 150ms ease, box-shadow 150ms ease';active.style.top=`${target.top}px`;active.style.left=`${target.left}px`;setTimeout(()=>{placeholder.replaceWith(active);active.classList.remove('is-reordering');active.removeAttribute('style');document.body.classList.remove('public-menu-dragging');saveMenuOrder(list);try{handle.releasePointerCapture(pointerId)}catch{}drag=null},155)};list.addEventListener('pointerup',finish);list.addEventListener('pointercancel',finish);
  list.addEventListener('click',e=>{if(e.target.closest('.menu-drag')){e.preventDefault();e.stopPropagation()}});
  list.addEventListener('keydown',e=>{const h=e.target.closest('.menu-drag');if(!h||!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const row=h.closest('[data-menu-key]'),peers=[...list.querySelectorAll('[data-menu-key]')],i=peers.indexOf(row),j=e.key==='ArrowUp'?i-1:i+1;if(j<0||j>=peers.length)return;const before=new Map(peers.map(x=>[x,x.getBoundingClientRect()]));if(e.key==='ArrowUp')list.insertBefore(row,peers[j]);else list.insertBefore(row,peers[j].nextSibling);animateReflow(before);saveMenuOrder(list);h.focus()});
}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function decodePayload(){try{const raw=(location.hash.match(/(?:^#|&)d=([^&]+)/)||[])[1];if(!raw)return null;let b=raw.replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';const binary=atob(b);const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch{return null}}

function sharedHashParams(){try{return new URLSearchParams(location.hash.replace(/^#/,''))}catch{return new URLSearchParams()}}
async function loadSharedWelcome(){
  const params=sharedHashParams(),gatewayId=params.get('g')||'',projectId=params.get('p')||'';
  if(!gatewayId||!projectId)return null;
  const url=`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(projectId)}/databases/(default)/documents/papaGolfGateways/${encodeURIComponent(gatewayId)}`;
  const r=await fetch(url,{cache:'no-store'});
  if(!r.ok)throw new Error(r.status===404?'This Welcome has not been published yet.':`Shared Welcome unavailable (${r.status}).`);
  const doc=await r.json();
  const raw=doc?.fields?.payload?.stringValue;if(!raw)throw new Error('Shared Welcome data is incomplete.');
  return JSON.parse(raw);
}
async function loadPublicWelcomeData(){
  const snapshot=decodePayload();if(snapshot?.p)return snapshot;
  const params=sharedHashParams();if(params.get('g')&&params.get('p'))return await loadSharedWelcome();
  return null;
}
function mapsUrl(lat,lng){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+','+lng)}`}
function distanceKm(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b);const q=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function showHome(){document.getElementById('publicHome')?.classList.remove('hidden');document.querySelectorAll('.detail-panel').forEach(x=>x.classList.add('hidden'));scrollTo(0,0)}
function showPanel(id){document.getElementById('publicHome')?.classList.add('hidden');document.querySelectorAll('.detail-panel').forEach(x=>x.classList.toggle('hidden',x.id!==id));scrollTo(0,0)}
const PUBLIC_SECTION_PANELS={home:'',wifi:'wifiPanel',villa:'villaPanel',nearby:'nearbyPanel',stay:'stayPanel','whats-on':'whatsOnPanel',food:'foodPanel',wellness:'wellnessPanel',tours:'toursPanel',transport:'transportPanel',help:'emergencyPanel'};
function openRequestedPublicSection(){
  const section=String(sharedHashParams().get('s')||'').trim().toLowerCase();
  if(!section)return;
  const panel=PUBLIC_SECTION_PANELS[section];
  if(section==='home'){showHome();return}
  if(panel&&document.getElementById(panel))showPanel(panel);
}

function info(el,text,empty='Information has not been added yet.'){if(!el)return;el.innerHTML=text?`<p>${esc(text).replace(/\n/g,'<br>')}</p>`:`<p class="muted">${esc(empty)}</p>`}
function renderPlaces(host,items,villa){if(!host)return;if(!items.length){host.innerHTML='<div class="info-card"><p class="muted">No approved places have been added yet.</p></div>';return}host.innerHTML=items.map(x=>{const km=Number.isFinite(villa.lat)&&Number.isFinite(villa.lng)?distanceKm(villa.lat,villa.lng,x.lat,x.lng):null;return `<article class="place-card"><strong>${esc(x.name)}</strong><div class="place-meta">${esc((x.category||'place').replace(/-/g,' '))}${km!=null?' · '+km.toFixed(km<1?2:1)+' km away':''}</div>${x.note?`<div class="place-note">${esc(x.note)}</div>`:''}<a class="map-link" href="${mapsUrl(x.lat,x.lng)}" target="_blank" rel="noopener">Directions</a></article>`}).join('')}
function dayName(day){return ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(day)]||''}
function activityCard(a){const time=[a.startTime,a.endTime].filter(Boolean).join('–');return `<article class="activity-card"><div class="activity-head"><strong>${esc(a.title||'Activity')}</strong>${a.price?`<span>${esc(a.price)}</span>`:''}</div>${time?`<div class="activity-time">${esc(time)}</div>`:''}${a.note?`<p>${esc(a.note)}</p>`:''}${a.booking?`<div class="activity-booking"><strong>Booking:</strong> ${esc(a.booking)}</div>`:''}</article>`}
function renderActivities(items){
  const enabled=items.filter(x=>x.enabled!==false&&x.title);
  const today=new Date().getDay();const todayItems=enabled.filter(x=>(x.days||[]).map(Number).includes(today)).sort((a,b)=>String(a.startTime||'').localeCompare(String(b.startTime||'')));
  const todayHost=document.getElementById('todayActivities');
  if(todayHost)todayHost.innerHTML=todayItems.length?`<div class="today-label">Today · ${dayName(today)}</div>${todayItems.map(activityCard).join('')}`:'<div class="info-card"><p class="muted">Nothing scheduled for today.</p></div>';
  const weekly=document.getElementById('weeklyActivities');
  if(weekly){weekly.innerHTML=[1,2,3,4,5,6,0].map(day=>{const a=enabled.filter(x=>(x.days||[]).map(Number).includes(day)).sort((x,y)=>String(x.startTime||'').localeCompare(String(y.startTime||'')));return a.length?`<section class="day-group"><h4>${dayName(day)}</h4>${a.map(activityCard).join('')}</section>`:''}).join('')||'<div class="info-card"><p class="muted">No weekly activities have been published yet.</p></div>'}
  const tile=document.getElementById('whatsOnTile');if(tile)tile.classList.toggle('hidden',!enabled.length);
  const summary=document.getElementById('whatsOnSummary');if(summary)summary.textContent=todayItems.length?`${todayItems.length} ${todayItems.length===1?'activity':'activities'} today`:'Weekly activities';
  const strip=document.getElementById('publicTodayStrip'),stripSummary=document.getElementById('publicTodayStripSummary');
  if(strip){
    strip.classList.toggle('hidden',todayItems.length<2);
    if(stripSummary){const first=todayItems[0],firstTime=first?.startTime?`${first.startTime} · `:'',extra=todayItems.length>1?` + ${todayItems.length-1} more`:'';stripSummary.textContent=todayItems.length?`${firstTime}${first.title}${extra}`:''}
  }
}
async function init(){setupMenuReorder();let data=null;try{data=await loadPublicWelcomeData()}catch(err){const invalid=document.getElementById('invalidWelcome');invalid?.classList.remove('hidden');const p=invalid?.querySelector('p');if(p)p.textContent=err.message;document.getElementById('publicHome')?.classList.add('hidden');return}if(!data?.p){document.getElementById('publicHome')?.classList.add('hidden');document.getElementById('invalidWelcome')?.classList.remove('hidden');return}const y={g:true,s:true,e:true,n:true,f:true,w:true,t:true,r:true,o:true,h:true,...(data.y||{})};const q=data.p,v={propertyName:q.n||'',developer:q.d||'',unitName:q.u||'',address:q.a||'',lat:Number(q.la),lng:Number(q.lo),host:q.h||'',emergency:q.e||'',wifiName:q.w||'',wifiPassword:q.pw||'',bluetooth:q.b||'',villaInfo:q.g||'',stayDetails:{checkIn:q.ci||'',checkOut:q.co||'',facilities:q.fa||'',mapInfo:q.m||'',notices:q.nt||''},transportInfo:q.t||'',foodInfo:q.f||'',wellnessInfo:q.wl||'',toursInfo:q.tr||'',otherServices:q.o||''},p=(Array.isArray(data.x)?data.x:[]).map(x=>({name:x.n||'',category:x.c||'other',lat:Number(x.a),lng:Number(x.o),note:x.t||''})),activities=(Array.isArray(data.e)?data.e:[]).map(a=>({id:a.i||'',title:a.n||'',category:a.c||'activity',days:Array.isArray(a.d)?a.d:[],startTime:a.s||'',endTime:a.z||'',note:a.t||'',price:a.p||'',booking:a.b||'',enabled:a.en!==false}));document.getElementById('publicDeveloper').textContent=v.developer?`Managed by ${v.developer}`:'';document.getElementById('publicAddress').textContent=[v.propertyName,v.address].filter(Boolean).join(' · ');document.getElementById('publicHeading').textContent=`Welcome to ${v.propertyName||'your villa'}`;const unit=document.getElementById('publicUnit');if(unit){unit.textContent=v.unitName||'';unit.classList.toggle('hidden',!v.unitName)};document.getElementById('quickWifi').textContent=v.wifiName||'Open network details';document.getElementById('quickHost').textContent=v.host||'Contact information';const dir=document.getElementById('quickDirections');if(Number.isFinite(v.lat)&&Number.isFinite(v.lng))dir.href=mapsUrl(v.lat,v.lng);else{dir.removeAttribute('href');dir.querySelector('small').textContent='Location not added yet'}
  info(document.getElementById('villaInfo'),v.villaInfo,'Villa guide information has not been added yet.');info(document.getElementById('hostInfo'),v.host?`Host / manager\n${v.host}`:'','Host contact has not been added yet.');
  const stay=v.stayDetails||{},hasStay=[stay.checkIn,stay.checkOut,stay.facilities,stay.mapInfo,stay.notices].some(x=>String(x||'').trim());const stayTile=document.getElementById('stayTile');if(stayTile)stayTile.classList.toggle('hidden',!hasStay||y.s===false);const arrival=document.getElementById('arrivalInfo');if(arrival){const bits=[];if(stay.checkIn)bits.push(`<div><strong>Check-in</strong><br>${esc(stay.checkIn)}</div>`);if(stay.checkOut)bits.push(`<div><strong>Check-out</strong><br>${esc(stay.checkOut)}</div>`);arrival.classList.toggle('hidden',!bits.length);arrival.innerHTML=bits.length?`<div class="arrival-grid">${bits.join('')}</div>`:''}const facilities=document.getElementById('facilitiesInfo');if(facilities){facilities.classList.toggle('hidden',!stay.facilities);facilities.innerHTML=stay.facilities?`<p><strong>Facilities & opening hours</strong><br>${esc(stay.facilities).replace(/\n/g,'<br>')}</p>`:''}const mapInfo=document.getElementById('mapInfo');if(mapInfo){mapInfo.classList.toggle('hidden',!stay.mapInfo);mapInfo.innerHTML=stay.mapInfo?`<p><strong>Property map & wayfinding</strong><br>${esc(stay.mapInfo).replace(/\n/g,'<br>')}</p>`:''}const notices=document.getElementById('noticesInfo');if(notices){notices.classList.toggle('hidden',!stay.notices);notices.innerHTML=stay.notices?`<p><strong>Important notices</strong><br>${esc(stay.notices).replace(/\n/g,'<br>')}</p>`:''}
  const wifi=document.getElementById('wifiInfo');wifi.innerHTML=(v.wifiName||v.wifiPassword)?`<div class="wifi-row"><div><span>Wi-Fi network</span><strong>${esc(v.wifiName||'—')}</strong></div>${v.wifiName?'<button class="copy-btn" data-copy="wifiName">Copy</button>':''}</div><div class="wifi-row"><div><span>Password</span><strong>${esc(v.wifiPassword||'—')}</strong></div>${v.wifiPassword?'<button class="copy-btn" data-copy="wifiPassword">Copy</button>':''}</div>`:'<p class="muted">Wi-Fi information has not been added yet.</p>';info(document.getElementById('bluetoothInfo'),v.bluetooth,'No additional technology instructions.');
  info(document.getElementById('foodInfo'),v.foodInfo,'No food or delivery instructions have been added yet.');info(document.getElementById('wellnessInfo'),v.wellnessInfo,'No wellness or massage information has been added yet.');info(document.getElementById('toursInfo'),v.toursInfo,'No tour or excursion information has been added yet.');info(document.getElementById('transportInfo'),v.transportInfo,'No transport instructions have been added yet.');info(document.getElementById('otherServices'),y.o===false?'':v.otherServices,'No additional guest services have been added yet.');info(document.getElementById('emergencyInfo'),v.emergency?`Emergency information\n${v.emergency}`:'','Emergency information has not been added yet.');info(document.getElementById('emergencyHost'),v.host?`Host / property contact\n${v.host}`:'','Host contact has not been added yet.');
  renderActivities(y.e===false?[]:activities);renderPlaces(document.getElementById('nearbyList'),p,v);renderPlaces(document.getElementById('foodList'),p.filter(x=>['restaurant','bar','cafe'].includes(x.category)),v);renderPlaces(document.getElementById('tourList'),p.filter(x=>['activity','tour','attraction'].includes(x.category)),v);
  const villaTile=document.getElementById('villaTile');if(villaTile)villaTile.classList.toggle('hidden',y.g===false||!v.villaInfo);const nearbyTile=document.getElementById('nearbyTile');if(nearbyTile)nearbyTile.classList.toggle('hidden',y.n===false);document.getElementById('foodTile').classList.toggle('hidden',y.f===false||(!v.foodInfo&&!p.some(x=>['restaurant','bar','cafe'].includes(x.category))));document.getElementById('wellnessTile').classList.toggle('hidden',y.w===false||(!v.wellnessInfo&&!p.some(x=>x.category==='spa')));document.getElementById('toursTile').classList.toggle('hidden',y.t===false||(!v.toursInfo&&!p.some(x=>['activity','tour','attraction'].includes(x.category))));document.getElementById('transportTile').classList.toggle('hidden',y.r===false||(!v.transportInfo&&!(y.o!==false&&v.otherServices)&&!p.some(x=>x.category==='transport')));
  document.addEventListener('click',async e=>{const panel=e.target.closest('[data-panel]');if(panel){showPanel(panel.dataset.panel);return}if(e.target.closest('.back-btn')){showHome();return}const copy=e.target.closest('[data-copy]');if(copy){const val=v[copy.dataset.copy]||'';try{await navigator.clipboard.writeText(val);copy.textContent='Copied'}catch{copy.textContent='Select & copy'}}});
}
document.addEventListener('DOMContentLoaded',async()=>{await init();setTimeout(openRequestedPublicSection,0)});
window.addEventListener('hashchange',()=>setTimeout(openRequestedPublicSection,0));
